// Flat ESLint config for the PrimeThink compiled Live App template.
//
// WHY THIS EXISTS: Vite/esbuild does NOT enforce `no-undef` — it happily bundles
// code with undeclared references, so a typo or a missing import ships to
// production and only blows up at runtime. ESLint is the only gate that catches
// it, which is why `npm run build` runs it before `vite build`.
//
// Run it after EVERY edit: `npm run lint`.

import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';

export default [
  {
    // dist/ is build output; .flowbite-react/ is generated by the flowbite plugin.
    ignores: ['dist/**', 'node_modules/**', '.flowbite-react/**']
  },
  js.configs.recommended,
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.es2022,
        // `pt` is injected by the PrimeThink host before the app runs.
        pt: 'readonly'
      },
      parserOptions: {
        ecmaFeatures: { jsx: true }
      }
    },
    plugins: {
      'react-hooks': reactHooks
    },
    rules: {
      // The rule this whole setup is here for (see Issue #8 in the post-mortem).
      'no-undef': 'error',
      // caughtErrors:'none' — `catch (err) { /* ignore */ }` is idiomatic, not a defect.
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^[A-Z_]', caughtErrors: 'none' }],
      'no-console': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
      // React hooks correctness — these catch the stale-closure / conditional-hook
      // bugs that render as "works on my machine" and crash on a re-render.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn'
    }
  },
  {
    // Build scripts run in Node, not the browser.
    files: ['scripts/**/*.mjs', 'vite.config.js', 'eslint.config.js'],
    languageOptions: {
      globals: { ...globals.node }
    }
  }
];
