// Flat ESLint config for the PrimeThink compiled Live App template.
//
// WHY THIS EXISTS: Vite/esbuild does NOT enforce `no-undef` — it happily bundles
// code with undeclared references, so a typo or a missing import ships to
// production and only blows up at runtime. ESLint is the only gate that catches
// it, which is why `npm run build` runs it before `vite build`.
//
// Run it after EVERY edit: `npm run lint`.

import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import primethink from './eslint-rules/primethink.js';

export default [
  {
    // dist/ is build output; .flowbite-react/ is generated by the flowbite plugin.
    ignores: ['dist/**', 'node_modules/**', '.flowbite-react/**']
  },
  js.configs.recommended,
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.es2022,
        // `pt` is injected by the PrimeThink host before the app runs.
        pt: 'readonly'
      },
      parserOptions: {
        ecmaFeatures: { jsx: true }
      }
    },
    plugins: {
      'react-hooks': reactHooks,
      primethink
    },
    rules: {
      // The rule this whole setup is here for (see Issue #8 in the post-mortem).
      'no-undef': 'error',
      // caughtErrors:'none' — `catch (err) { /* ignore */ }` is idiomatic, not a defect.
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^[A-Z_]', caughtErrors: 'none' }],
      'no-console': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
      // React hooks correctness — these catch the stale-closure / conditional-hook
      // bugs that render as "works on my machine" and crash on a re-render.
      'react-hooks/rules-of-hooks': 'error',
      // A hook-dependency warning is usually a state-lifetime bug, not a style nit:
      // treat it as a finding and read it before shipping.
      'react-hooks/exhaustive-deps': 'warn',

      // PrimeThink platform rules. These replace the regex-based pt-doctor checks —
      // see eslint-rules/primethink.js for why the AST version matters.
      'primethink/response-message-field': 'error',
      'primethink/on-entity-changed-arg-order': 'error',
      'primethink/list-entities-without-metadata': 'error',
      'primethink/no-flowbite-modal': 'error',
      'primethink/no-web-storage': 'error',
      'primethink/add-message-hidden': 'error',
      'primethink/no-pt-write-in-state-updater': 'error'
    }
  },
  {
    // Build scripts, tests and config run in Node, not the browser.
    files: [
      'scripts/**/*.mjs',
      'tests/**/*.mjs',
      'eslint-rules/**/*.{js,mjs}',
      'vite.config.js',
      'eslint.config.js',
      'playwright.config.mjs'
    ],
    languageOptions: {
      globals: { ...globals.node }
    }
  },
  {
    // EVERY file under tests/, not just *.spec.mjs. A Playwright helper is serialised
    // and run in the BROWSER too (page.evaluate bodies, addInitScript), so it
    // legitimately references document and window. Scoped to *.spec.mjs this was a
    // hard build failure under --max-warnings 0, and two projects each fixed it by
    // hand — one of them three times, as it added a helper per test kind.
    files: ['tests/**/*.mjs'],
    languageOptions: {
      globals: { ...globals.node, ...globals.browser }
    },
    rules: {
      // Intl formats money with a narrow no-break space: `12,50 €`. Asserting that
      // exact string is correct, and trips no-irregular-whitespace — which under
      // --max-warnings 0 fails the build for any app formatting a European currency.
      'no-irregular-whitespace': ['error', { skipStrings: true, skipTemplates: true }]
    }
  }
];
